In [1]:
import numpy as np

In [2]:
class fuzzy_set_ops:
    def fuzzy_union(A, B):
        return np.maximum(A, B)

    def fuzzy_intersection(A, B):
        return np.minimum(A, B)

    def fuzzy_complement(A):
        return 1-A

    def fuzzy_difference(A, B):
        return np.maximum(A, 1-B)

In [3]:
class fuzzy_set_relations:
    def cartesian_product(A, B):
        return np.outer(A, B)

    def minmax_composition(R, S):
        return np.max(np.minimum.outer(R, S), axis = 1)

In [6]:
#defining fuzzy sets
A = np.array([0.2, 0.4, 0.6, 0.8])
B = np.array([0.3, 0.5, 0.7, 0.9])

print("Set A: ", A)
print("Set B: ", B)

#performing fuzzy operations
print("Union of sets: ", fuzzy_set_ops.fuzzy_union(A, B))
print("Intersection of sets: ", fuzzy_set_ops.fuzzy_intersection(A, B))
print("Complement of set A: ", fuzzy_set_ops.fuzzy_complement(A))
print("Difference of sets: ", fuzzy_set_ops.fuzzy_difference(A, B))

Set A:  [0.2 0.4 0.6 0.8]
Set B:  [0.3 0.5 0.7 0.9]
Union of sets:  [0.3 0.5 0.7 0.9]
Intersection of sets:  [0.2 0.4 0.6 0.8]
Complement of set A:  [0.8 0.6 0.4 0.2]
Difference of sets:  [0.7 0.5 0.6 0.8]


In [8]:
#cartesian product
print("Cartesian Product of sets: \n", fuzzy_set_relations.cartesian_product(A, B))

Cartesian Product of sets: 
 [[0.06 0.1  0.14 0.18]
 [0.12 0.2  0.28 0.36]
 [0.18 0.3  0.42 0.54]
 [0.24 0.4  0.56 0.72]]


In [10]:
#defining relations for min max composition
R = np.array([0.2, 0.5, 0.8])
S = np.array([0.3, 0.6, 0.7])

print("Min Max Composition of relations: \n", fuzzy_set_relations.minmax_composition(R, S))

Min Max Composition of relations: 
 [0.2 0.5 0.7]
